### PR TITLE
first cam found is the master

### PR DESCRIPTION
**Pull request by 0x72D0**
## Description
provider_vision now take the first detected cam as the master

### CODE REVIEW

**Comment by supertoto29** [comment]
@0x72D0 Not sure it's a great idea just to remove a camera. A warning could be sent on /rosout just to know that there is a cam missing.

**Review by supertoto29 — CHANGES_REQUESTED** [review]
Add error on ros_stream that the camera is missing

**Comment by 0x72D0** [comment]
@supertoto29 not sure what do you mean by removing a camera, no camera is removed from the array. The modification is that the first camera founs is the master.

**Comment by 0x72D0** [comment]
there's already an error when a camera is missing

**Comment by supertoto29** [comment]
If there is a error on the roscore, I dont see the problem with the changes. You can re request the review and I will approuve it

**Review by supertoto29 — APPROVED** [review]
LGTM!

**Pull request merged**
