### PR TITLE
removed Slack notifications

### LINKED ISSUE #25: Remove Slack Notifications
## Expected Enhancement
Slack notifications should be deleted

## Current Behavior
Slack is still notified when changes are made on the branch

## Possible Solution
Remove Slack notifications from .github folder

### LINKED ISSUE #27: Update to ROS Noetic
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
Action should be working with noetic

## Current Behavior
Multiple package used by provider vision are for melodic.

## Possible Solution
Change the package in the docker compose file for noetic

## Environment Used
- Project version : 1.0.0
- docker version : 20.10.5
- docker-compose version : 1.28.5

### PR DESCRIPTION
**Pull request by Kam0ss**
## Description
Removed Slack notifications.

## Fixes
Link all the related issues from the issue tracker
- Closes: #25 

## Checklist
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Review by supertoto29 — DISMISSED** [review]
LGTM!

**Comment by supertoto29** [comment]
@0x72D0 Branch is still not passing the action. Is this going to be resolved?

**Comment by 0x72D0** [comment]
yup but I need to configure stuff on my pc first

**Review by 0x72D0 — APPROVED** [review]
LGTM!

**Pull request merged**
